export const StoryData = [
  {
    id: 'BlackLake',
    name: ' Black-water\n          Lake',
    videoUrl: 'https://findtruman.io/assets/neo/media/HSH.mp4',
    gameSceneUrl: 'https://findtruman.io/fcc/scenes/game-black-water',
    storySceneUrl: 'https://findtruman.io/fcc/scenes/story-black-water',
  },
  {
    id: 'Metaverse',
    name: 'Metaverse\n   Carnival',
    videoUrl: 'https://findtruman.io/assets/neo/media/YYZJNH.mp4',
    gameSceneUrl: 'https://findtruman.io/fcc/scenes/game-the-trip',
    storySceneUrl: 'https://findtruman.io/fcc/scenes/story-the-trip',
  },
  {
    id: 'Church',
    name: 'Scarlet Church',
    videoUrl: 'https://findtruman.io/assets/neo/media/XSJT.mp4',
    gameSceneUrl: 'https://findtruman.io/fcc/scenes/game-scarlet-church',
    storySceneUrl: 'https://findtruman.io/fcc/scenes/story-scarlet-church',
  },
  {
    id: 'PoliceStation',
    name: 'Police Station',
    videoUrl: '',
    gameSceneUrl: '',
    storySceneUrl: 'https://findtruman.io/fcc/scenes/story-police-station',
  },
  {
    id: 'Hospital',
    name: 'Hospital',
    videoUrl: '',
    gameSceneUrl: '',
    storySceneUrl: 'https://findtruman.io/fcc/scenes/story-hospital',
  },
  {
    id: 'Beelzebub',
    name: 'Beelzebub',
    videoUrl: 'https://findtruman.io/assets/neo/media/XSJT.mp4',
    gameSceneUrl: 'https://findtruman.io/fcc/scenes/game-the-abyss',
    storySceneUrl: '',
  },
  {
    id: 'SevenDeadlySins',
    name: 'Seven Deadly\n           Sins',
    videoUrl: 'https://findtruman.io/assets/index-assets/HQ-FT-launch-ENG.mp4',
    twitterUrl:
      'https://twitter.com/search?q=(%23FT_Alpha_Test)%20(from%3AThomas26670%20OR%20from%3AAngelic25314540%20OR%20from%3AAxe509%20OR%20from%3AVincent10679122%20OR%20from%3AFindTruman)&src=typed_query&f=live',
  },
  {
    id: 'BlackLake',
    name: ' Black-water\n          Lake',
    videoUrl: 'https://findtruman.io/assets/neo/media/HSH.mp4',
    gameSceneUrl: 'https://findtruman.io/fcc/scenes/game-black-water',
    storySceneUrl: 'https://findtruman.io/fcc/scenes/story-black-water',
  },
  {
    id: 'Metaverse',
    name: 'Metaverse\n   Carnival',
    videoUrl: 'https://findtruman.io/assets/neo/media/YYZJNH.mp4',
    gameSceneUrl: 'https://findtruman.io/fcc/scenes/game-the-trip',
    storySceneUrl: 'https://findtruman.io/fcc/scenes/story-the-trip',
  },
  {
    id: 'Church',
    name: 'Scarlet Church',
    videoUrl: 'https://findtruman.io/assets/neo/media/XSJT.mp4',
    gameSceneUrl: 'https://findtruman.io/fcc/scenes/game-scarlet-church',
    storySceneUrl: 'https://findtruman.io/fcc/scenes/story-scarlet-church',
  },
  {
    id: 'PoliceStation',
    name: 'Police Station',
    videoUrl: '',
    gameSceneUrl: '',
    storySceneUrl: 'https://findtruman.io/fcc/scenes/story-police-station',
  },
  {
    id: 'Hospital',
    name: 'Hospital',
    videoUrl: '',
    gameSceneUrl: '',
    storySceneUrl: 'https://findtruman.io/fcc/scenes/story-hospital',
  },
  {
    id: 'Beelzebub',
    name: 'Beelzebub',
    videoUrl: 'https://findtruman.io/assets/neo/media/XSJT.mp4',
    gameSceneUrl: 'https://findtruman.io/fcc/scenes/game-the-abyss',
    storySceneUrl: '',
  },
  {
    id: 'SevenDeadlySins',
    name: 'Seven Deadly\n           Sins',
    videoUrl: 'https://findtruman.io/assets/index-assets/HQ-FT-launch-ENG.mp4',
    twitterUrl:
      'https://twitter.com/search?q=(%23FT_Alpha_Test)%20(from%3AThomas26670%20OR%20from%3AAngelic25314540%20OR%20from%3AAxe509%20OR%20from%3AVincent10679122%20OR%20from%3AFindTruman)&src=typed_query&f=live',
  },
  {
    id: 'BlackLake',
    name: ' Black-water\n          Lake',
    videoUrl: 'https://findtruman.io/assets/neo/media/HSH.mp4',
    gameSceneUrl: 'https://findtruman.io/fcc/scenes/game-black-water',
    storySceneUrl: 'https://findtruman.io/fcc/scenes/story-black-water',
  },
  {
    id: 'Metaverse',
    name: 'Metaverse\n   Carnival',
    videoUrl: 'https://findtruman.io/assets/neo/media/YYZJNH.mp4',
    gameSceneUrl: 'https://findtruman.io/fcc/scenes/game-the-trip',
    storySceneUrl: 'https://findtruman.io/fcc/scenes/story-the-trip',
  },
  {
    id: 'Church',
    name: 'Scarlet Church',
    videoUrl: 'https://findtruman.io/assets/neo/media/XSJT.mp4',
    gameSceneUrl: 'https://findtruman.io/fcc/scenes/game-scarlet-church',
    storySceneUrl: 'https://findtruman.io/fcc/scenes/story-scarlet-church',
  },
  {
    id: 'PoliceStation',
    name: 'Police Station',
    videoUrl: '',
    gameSceneUrl: '',
    storySceneUrl: 'https://findtruman.io/fcc/scenes/story-police-station',
  },
  {
    id: 'Hospital',
    name: 'Hospital',
    videoUrl: '',
    gameSceneUrl: '',
    storySceneUrl: 'https://findtruman.io/fcc/scenes/story-hospital',
  },
  {
    id: 'Beelzebub',
    name: 'Beelzebub',
    videoUrl: 'https://findtruman.io/assets/neo/media/XSJT.mp4',
    gameSceneUrl: 'https://findtruman.io/fcc/scenes/game-the-abyss',
    storySceneUrl: '',
  },
  {
    id: 'SevenDeadlySins',
    name: 'Seven Deadly\n           Sins',
    videoUrl: 'https://findtruman.io/assets/index-assets/HQ-FT-launch-ENG.mp4',
    twitterUrl:
      'https://twitter.com/search?q=(%23FT_Alpha_Test)%20(from%3AThomas26670%20OR%20from%3AAngelic25314540%20OR%20from%3AAxe509%20OR%20from%3AVincent10679122%20OR%20from%3AFindTruman)&src=typed_query&f=live',
  },
];
