export const StoryData = [
  {
    id: 1,
    name: 'Black-water\nLake',
    img: 'https://findtruman.io/assets/badges/4.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/HSH.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-black-water-lake',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-black-water-lake',
  },
  {
    id: 2,
    name: 'Metaverse\nCarnival',
    img: 'https://findtruman.io/assets/badges/7.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/YYZJNH.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-the-trip',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-the-trip',
  },
  {
    id: 3,
    name: 'Scarlet\nChurch',
    img: 'https://findtruman.io/assets/badges/6.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/XSJT.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-scarlet-church',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-scarlet-church',
  },
  {
    id: 4,
    name: 'Black-water\nLake',
    img: 'https://findtruman.io/assets/badges/4.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/HSH.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-black-water-lake',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-black-water-lake',
  },
  {
    id: 5,
    name: 'Metaverse\nCarnival',
    img: 'https://findtruman.io/assets/badges/7.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/YYZJNH.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-the-trip',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-the-trip',
  },
  {
    id: 6,
    name: 'Scarlet\nChurch',
    img: 'https://findtruman.io/assets/badges/6.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/XSJT.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-scarlet-church',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-scarlet-church',
  },
  {
    id: 7,
    name: 'Black-water\nLake',
    img: 'https://findtruman.io/assets/badges/4.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/HSH.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-black-water-lake',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-black-water-lake',
  },
  {
    id: 8,
    name: 'Metaverse\nCarnival',
    img: 'https://findtruman.io/assets/badges/7.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/YYZJNH.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-the-trip',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-the-trip',
  },
  {
    id: 9,
    name: 'Scarlet\nChurch',
    img: 'https://findtruman.io/assets/badges/6.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/XSJT.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-scarlet-church',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-scarlet-church',
  },
  {
    id: 10,
    name: 'Black-water\nLake',
    img: 'https://findtruman.io/assets/badges/4.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/HSH.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-black-water-lake',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-black-water-lake',
  },
  {
    id: 11,
    name: 'Metaverse\nCarnival',
    img: 'https://findtruman.io/assets/badges/7.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/YYZJNH.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-the-trip',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-the-trip',
  },
  {
    id: 12,
    name: 'FindTruman',
    img: 'https://findtruman.io/assets/badges/7.png',
    url: 'https://twitter.com/FindTruman',
  },
  {
    id: 1,
    name: 'Black-water\nLake',
    img: 'https://findtruman.io/assets/badges/4.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/HSH.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-black-water-lake',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-black-water-lake',
  },
  {
    id: 2,
    name: 'Metaverse\nCarnival',
    img: 'https://findtruman.io/assets/badges/7.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/YYZJNH.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-the-trip',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-the-trip',
  },
  {
    id: 3,
    name: 'Scarlet\nChurch',
    img: 'https://findtruman.io/assets/badges/6.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/XSJT.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-scarlet-church',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-scarlet-church',
  },
  {
    id: 4,
    name: 'Black-water\nLake',
    img: 'https://findtruman.io/assets/badges/4.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/HSH.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-black-water-lake',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-black-water-lake',
  },
  {
    id: 5,
    name: 'Metaverse\nCarnival',
    img: 'https://findtruman.io/assets/badges/7.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/YYZJNH.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-the-trip',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-the-trip',
  },
  {
    id: 6,
    name: 'Scarlet\nChurch',
    img: 'https://findtruman.io/assets/badges/6.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/XSJT.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-scarlet-church',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-scarlet-church',
  },
  {
    id: 7,
    name: 'Black-water\nLake',
    img: 'https://findtruman.io/assets/badges/4.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/HSH.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-black-water-lake',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-black-water-lake',
  },
  {
    id: 8,
    name: 'Metaverse\nCarnival',
    img: 'https://findtruman.io/assets/badges/7.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/YYZJNH.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-the-trip',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-the-trip',
  },
  {
    id: 9,
    name: 'Scarlet\nChurch',
    img: 'https://findtruman.io/assets/badges/6.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/XSJT.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-scarlet-church',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-scarlet-church',
  },
  {
    id: 10,
    name: 'Black-water\nLake',
    img: 'https://findtruman.io/assets/badges/4.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/HSH.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-black-water-lake',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-black-water-lake',
  },
  {
    id: 11,
    name: 'Metaverse\nCarnival',
    img: 'https://findtruman.io/assets/badges/7.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/YYZJNH.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-the-trip',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-the-trip',
  },
  {
    id: 12,
    name: 'FindTruman',
    img: 'https://findtruman.io/assets/badges/7.png',
    url: 'https://twitter.com/FindTruman',
  },
  {
    id: 1,
    name: 'Black-water\nLake',
    img: 'https://findtruman.io/assets/badges/4.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/HSH.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-black-water-lake',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-black-water-lake',
  },
  {
    id: 2,
    name: 'Metaverse\nCarnival',
    img: 'https://findtruman.io/assets/badges/7.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/YYZJNH.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-the-trip',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-the-trip',
  },
  {
    id: 3,
    name: 'Scarlet\nChurch',
    img: 'https://findtruman.io/assets/badges/6.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/XSJT.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-scarlet-church',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-scarlet-church',
  },
  {
    id: 4,
    name: 'Black-water\nLake',
    img: 'https://findtruman.io/assets/badges/4.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/HSH.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-black-water-lake',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-black-water-lake',
  },
  {
    id: 5,
    name: 'Metaverse\nCarnival',
    img: 'https://findtruman.io/assets/badges/7.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/YYZJNH.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-the-trip',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-the-trip',
  },
  {
    id: 6,
    name: 'Scarlet\nChurch',
    img: 'https://findtruman.io/assets/badges/6.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/XSJT.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-scarlet-church',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-scarlet-church',
  },
  {
    id: 7,
    name: 'Black-water\nLake',
    img: 'https://findtruman.io/assets/badges/4.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/HSH.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-black-water-lake',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-black-water-lake',
  },
  {
    id: 8,
    name: 'Metaverse\nCarnival',
    img: 'https://findtruman.io/assets/badges/7.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/YYZJNH.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-the-trip',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-the-trip',
  },
  {
    id: 9,
    name: 'Scarlet\nChurch',
    img: 'https://findtruman.io/assets/badges/6.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/XSJT.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-scarlet-church',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-scarlet-church',
  },
  {
    id: 10,
    name: 'Black-water\nLake',
    img: 'https://findtruman.io/assets/badges/4.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/HSH.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-black-water-lake',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-black-water-lake',
  },
  {
    id: 11,
    name: 'Metaverse\nCarnival',
    img: 'https://findtruman.io/assets/badges/7.png',
    videoUrl: 'https://findtruman.io/assets/neo/media/YYZJNH.mp4',
    gameSceneUrl: 'https://findtruman.io/neo/scenes/game-the-trip',
    storySceneUrl: 'https://findtruman.io/neo/scenes/story-the-trip',
  },
  {
    id: 12,
    name: 'FindTruman',
    img: 'https://findtruman.io/assets/badges/7.png',
    url: 'https://twitter.com/FindTruman',
  },
];
